server:
  port: 9901
spring:
  application:
    name: tensquare-base
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.128:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    show-sql: true
    database: mysql
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868
  instance:
    prefer-ip-address: true